name = "light6-chat"
main = "src/worker.mjs"
compatibility_date = "2024-01-01"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "light6-chat-db"
database_id = "051b0e1e-4eea-4234-b7c1-7c68d7ff001a"

# 环境变量
[vars]
JWT_SECRET = "your-jwt-secret" # 替换为您的 JWT 密钥

# 开发环境配置
[dev]
port = 8787
local_protocol = "http" 